### ISSUE TITLE
Passing args to minimize 

### ISSUE THREAD

**Issue by AhmedThahir** [rfeinman/pytorch-minimize#36] opened 2024-11-08 17:57 UTC
Hi there.
Great work on this library! 

I would like to know how to pass arguments to the objective function. 

In scipy minimize, we can pass arguments using `args`.

**Comment by AhmedThahir** [comment] 2024-12-01 19:07
Any updates?

**Comment by rfeinman** [comment] 2024-12-01 19:52
Hi, I would recommend that you wrap your function using functools.partial if you need to pass additional arguments beyond the parameter being optimized.

**Comment by AhmedThahir** [comment] 2024-12-01 20:03
Could you give a starter example or share any resources?

**Comment by rfeinman** [comment] 2024-12-02 02:31
This issue is a duplicate of https://github.com/rfeinman/pytorch-minimize/issues/12

Please see the thread there for suggestions

**Closed** 2024-12-02 02:32 UTC

**Comment by AhmedThahir** [comment] 2024-12-02 07:49
Thanks!
